name: Production Release

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: '1'

permissions:
  contents: write
  packages: write

jobs:
  echo_start:
    name: Echo Start
    runs-on: ubuntu-24.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello, shall we start?"
  publish_release:
    name: Publish Release
    runs-on: ubuntu-24.04
    environment:
      name: production
    steps:
      - name: Start release
        run: |
          echo "Let's start the release!"